//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.09 at 05:11:21 PM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "localhost/clubs", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package hr.franmatesic.projectiis.dto.soap;
